'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { Progress } from '@/components/ui/progress';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from '@/components/ui/dialog';
import { toast } from 'sonner';
import { apiCall, getAuthToken } from '@/lib/api-client';
import { DocumentUpload } from '@/components/shared/document-upload';
import { DocumentViewer } from '@/components/shared/document-viewer';
import { MarkdownContent } from '@/components/shared/markdown-content';
import { useDataStore } from '@/store/data-store';
import { useClientsStore } from '@/store/clients-store';
import { generatePDF, downloadPDF } from '@/lib/pdf-generator';
import { v4 as uuidv4 } from 'uuid';
import {
  Loader2, Scale, Sparkles, FileText, Download, Save, Briefcase, Users, CheckCircle2,
  Zap, RotateCcw, FileDown, Eye, Pencil, MessageSquare
} from 'lucide-react';

interface FormField {
  key: string;
  label: string;
  placeholder: string;
  type?: 'text' | 'textarea' | 'date' | 'number';
  half?: boolean;
}

interface ViewConfig {
  title: string;
  description: string;
  icon: React.ElementType;
  apiEndpoint: string;
  apiTask?: string;
  documentType?: string;
  module: 'civil' | 'criminal' | 'family' | 'execution';
  formFields: FormField[];
  getResultContent: (res: any) => string;
}

interface DraftingViewProps {
  config: ViewConfig;
}

type FlowStage = 'idle' | 'extracting' | 'generating' | 'done' | 'error';

function useAutonomousDrafting(config: ViewConfig) {
  const [formData, setFormData] = useState<Record<string, string>>({});
  const [extractedText, setExtractedText] = useState('');
  const [extractedData, setExtractedData] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState('');
  const [error, setError] = useState('');
  const [viewerOpen, setViewerOpen] = useState(false);
  const [stage, setStage] = useState<FlowStage>('idle');
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [uploadedFileName, setUploadedFileName] = useState('');
  const [progress, setProgress] = useState(0);
  const [progressLabel, setProgressLabel] = useState('');
  const autoGenTimerRef = useRef<NodeJS.Timeout | null>(null);
  const formDataRef = useRef<Record<string, string>>({});
  formDataRef.current = formData;

  const cases = useDataStore((s) => s.cases);
  const clients = useClientsStore((s) => s.clients);
  const addDocument = useDataStore((s) => s.addDocument);

  const updateField = (key: string, value: string) => {
    setFormData((prev) => ({ ...prev, [key]: value }));
  };

  // Smart field mapping: matches extracted data keys to form field keys
  const mapExtractedToFormFields = (sd: any): Record<string, string> => {
    const newFormData: Record<string, string> = {};

    // Direct key match
    config.formFields.forEach((field) => {
      const val =
        sd[field.key] ||
        sd[field.key.toLowerCase()] ||
        sd[field.label.toLowerCase()] ||
        sd[field.label.replace(/\s+/g, '').toLowerCase()] ||
        '';
      if (val) {
        newFormData[field.key] = Array.isArray(val) ? val.join(', ') : String(val);
      }
    });

    // Common field aliases from AI extraction
    const aliasMap: Record<string, string[]> = {
      plaintiffName: ['plaintiffName', 'plaintiff', 'plaintiffName1', 'complainantName'],
      defendantName: ['defendantName', 'defendant', 'respondentName', 'opposingParty'],
      applicantName: ['applicantName', 'applicant', 'petitionerName', 'petitioner'],
      respondentName: ['respondentName', 'respondent', 'opposingParty', 'defendantName'],
      petitionerName: ['petitionerName', 'petitioner', 'applicantName'],
      accusedName: ['accusedName', 'accused', 'accused1', 'a1Name'],
      complainantName: ['complainantName', 'complainant', 'plaintiffName'],
      firNumber: ['firNumber', 'firNo', 'fir_no', 'firnumber'],
      policeStation: ['policeStation', 'psName', 'police_station'],
      courtName: ['courtName', 'court', 'courtDetails'],
      sectionsCharged: ['sectionsCharged', 'sections', 'underSections', 'ipcSections'],
      causeOfAction: ['causeOfAction', 'cause', 'cause_of_action'],
      facts: ['facts', 'factsOfCase', 'matterFacts', 'caseFacts', 'briefFacts'],
      grounds: ['grounds', 'groundsForBail', 'groundsForRelief'],
      reliefSought: ['reliefSought', 'relief', 'prayer', 'prayerSought'],
      prayer: ['prayer', 'reliefSought', 'relief'],
      impugnedOrder: ['impugnedOrder', 'impugned', 'challengedOrder', 'orderDate'],
      fundamentalRights: ['fundamentalRights', 'fundamentalRight', 'violatedRights'],
      natureOfViolence: ['natureOfViolence', 'violenceType', 'typeOfViolence'],
      subjectMatter: ['subjectMatter', 'subject', 'propertyDetails'],
    };

    // Apply alias mapping
    Object.entries(aliasMap).forEach(([target, aliases]) => {
      if (!newFormData[target] && config.formFields.find(f => f.key === target)) {
        for (const alias of aliases) {
          if (sd[alias]) {
            newFormData[target] = Array.isArray(sd[alias])
              ? sd[alias].join(', ')
              : String(sd[alias]);
            break;
          }
        }
      }
    });

    // Extract from nested objects (parties array, opposingParties, etc.)
    if (sd.parties && Array.isArray(sd.parties)) {
      sd.parties.forEach((p: any) => {
        const role = (p.role || '').toLowerCase();
        if (role.includes('plaintiff') || role.includes('complainant') || role.includes('petitioner') || role.includes('applicant')) {
          if (p.name && config.formFields.find(f => f.key === 'plaintiffName' || f.key === 'petitionerName' || f.key === 'applicantName')) {
            newFormData.plaintiffName = newFormData.plaintiffName || p.name;
            if (p.address) newFormData.plaintiffAddress = newFormData.plaintiffAddress || p.address;
          }
        }
        if (role.includes('defendant') || role.includes('respondent') || role.includes('opposing')) {
          if (p.name && config.formFields.find(f => f.key === 'defendantName' || f.key === 'respondentName')) {
            newFormData.defendantName = newFormData.defendantName || p.name;
            if (p.address) newFormData.defendantAddress = newFormData.defendantAddress || p.address;
          }
        }
        if (role.includes('accused')) {
          if (p.name && config.formFields.find(f => f.key === 'accusedName')) {
            newFormData.accusedName = newFormData.accusedName || p.name;
            if (p.phone) newFormData.accusedPhone = newFormData.accusedPhone || p.phone;
          }
        }
      });
    }

    if (sd.opposingParties && Array.isArray(sd.opposingParties) && sd.opposingParties.length > 0) {
      const op = sd.opposingParties[0];
      if (config.formFields.find(f => f.key === 'respondentName')) newFormData.respondentName = newFormData.respondentName || op.name;
      if (config.formFields.find(f => f.key === 'defendantName')) newFormData.defendantName = newFormData.defendantName || op.name;
    }

    if (sd.caseDetails) {
      const cd = sd.caseDetails;
      if (cd.firNumber && config.formFields.find(f => f.key === 'firNumber')) newFormData.firNumber = newFormData.firNumber || cd.firNumber;
      if (cd.policeStation && config.formFields.find(f => f.key === 'policeStation')) newFormData.policeStation = newFormData.policeStation || cd.policeStation;
      if (cd.causeOfAction && config.formFields.find(f => f.key === 'causeOfAction')) newFormData.causeOfAction = newFormData.causeOfAction || cd.causeOfAction;
      if (cd.reliefSought && config.formFields.find(f => f.key === 'reliefSought')) newFormData.reliefSought = newFormData.reliefSought || cd.reliefSought;
      if (cd.facts && config.formFields.find(f => f.key === 'facts')) newFormData.facts = newFormData.facts || (Array.isArray(cd.facts) ? cd.facts.join('\n') : cd.facts);
      if (cd.judgeName && config.formFields.find(f => f.key === 'judgeName')) newFormData.judgeName = newFormData.judgeName || cd.judgeName;
    }

    return newFormData;
  };

  // CORE AUTONOMOUS FLOW: After extraction, auto-trigger generation
  const processExtractedAndGenerate = useCallback((text: string, structuredData: any, fileName?: string) => {
    setExtractedText(text);
    setExtractedData(structuredData);
    setUploadedFileName(fileName || '');
    setStage('extracting');
    setProgress(60);
    setProgressLabel('AI filling form fields...');

    // Auto-fill ALL form fields from extracted data
    if (structuredData) {
      const newFormData = mapExtractedToFormFields(structuredData);
      setFormData(prev => ({ ...prev, ...newFormData }));
    }

    // AUTO-GENERATE: After extraction, automatically generate the draft
    setStage('generating');
    setProgress(75);
    setProgressLabel('AI drafting document...');

    autoGenTimerRef.current = setTimeout(() => {
      performGenerate(text, structuredData);
    }, 600);
  }, [config.formFields]);

  // Handle file upload extraction (called by DocumentUpload component)
  const handleExtracted = useCallback((data: { text: string; structuredData: any; fileName?: string }) => {
    processExtractedAndGenerate(data.text, data.structuredData, data.fileName);
  }, [processExtractedAndGenerate]);

  // Handle description-based extraction
  const handleDescriptionSubmit = useCallback(async (description: string) => {
    if (!description.trim()) {
      toast.error('Please describe the case or issue');
      return;
    }

    setLoading(true);
    setStage('extracting');
    setProgress(20);
    setProgressLabel('AI analyzing description...');

    try {
      const token = getAuthToken();

      // Step 1: Extract structured data from description
      setProgress(40);
      setProgressLabel('Extracting case details...');

      let structuredData: any = null;
      try {
        const dataRes = await apiCall('/ai-extract-data', {
          text: description.substring(0, 8000),
          module: config.module,
        }, token || undefined);
        structuredData = dataRes.data || dataRes.extracted || dataRes;
      } catch (e) {
        console.warn('Data extraction from description failed, using raw text');
      }

      setProgress(60);
      setProgressLabel('AI filling form fields...');

      // Step 2: Auto-fill and generate
      processExtractedAndGenerate(description, structuredData || {});
    } catch (err: any) {
      setError(err?.message || 'Analysis failed');
      setStage('error');
      toast.error(err?.message || 'Failed to analyze description');
    }
    setLoading(false);
  }, [config.module, processExtractedAndGenerate]);

  const performGenerate = useCallback(async (extractedContent: string, mergedData: Record<string, string>) => {
    setLoading(true);
    setResult('');
    setError('');
    setStage('generating');
    setProgress(80);
    setProgressLabel('AI drafting document...');
    try {
      const body: any = {};
      if (config.apiTask) body.task = config.apiTask;
      if (config.documentType) body.documentType = config.documentType;
      if (extractedContent) body.extractedText = extractedContent;
      // Include all form data + extracted data
      const currentFormData = formDataRef.current;
      Object.keys({ ...currentFormData, ...mergedData }).forEach((k) => {
        const val = mergedData[k] || currentFormData[k];
        if (val && typeof val === 'string' && val.trim()) body[k] = val;
      });

      const token = getAuthToken();
      const res = await apiCall(config.apiEndpoint, body, token || undefined);
      const content = config.getResultContent(res);
      setResult(content);
      setStage('done');
      setAutoGenerated(true);
      setProgress(100);
      setProgressLabel('Complete');
      toast.success('Document generated successfully');
    } catch (err: any) {
      setError(err?.message || 'Generation failed');
      setStage('error');
      toast.error(err?.message || 'Failed to generate document');
    }
    setLoading(false);
  }, [config]);

  const handleGenerate = useCallback(async () => {
    if (autoGenTimerRef.current) {
      clearTimeout(autoGenTimerRef.current);
      autoGenTimerRef.current = null;
    }
    setProgress(70);
    setProgressLabel('Generating draft...');
    await performGenerate(extractedText, formData);
  }, [extractedText, formData, performGenerate]);

  const handleSaveDocument = (content: string) => {
    setResult(content);
    toast.success('Document updated');
  };

  const handleSaveToCase = (caseId: string) => {
    if (!result || !caseId) return;
    const docItem = {
      id: uuidv4(),
      name: `${config.title} - ${new Date().toLocaleDateString('en-IN')}`,
      type: 'draft',
      category: config.module,
      content: result,
      caseId,
      createdAt: new Date().toISOString(),
    };
    addDocument(docItem);
    toast.success('Document saved to case');
  };

  // PDF Download
  const handleDownloadPDF = () => {
    if (!result) return;
    const doc = generatePDF(result, config.title);
    downloadPDF(doc, `${config.title.toLowerCase().replace(/ /g, '-')}.pdf`);
    toast.success('PDF downloaded');
  };

  // DOC Download
  const handleDownloadDOC = () => {
    if (!result) return;
    const htmlContent = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head><meta charset='utf-8'><title>${config.title}</title>
      <style>body{font-family:'Times New Roman',serif;font-size:12pt;line-height:1.6;margin:1in;}h1{font-size:16pt;font-weight:bold;}h2{font-size:14pt;font-weight:bold;}</style></head>
      <body>${result.replace(/\n/g, '<br>')}</body></html>`;
    const blob = new Blob([htmlContent], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.title.toLowerCase().replace(/ /g, '-')}.doc`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('DOC downloaded');
  };

  const resetFlow = useCallback(() => {
    if (autoGenTimerRef.current) {
      clearTimeout(autoGenTimerRef.current);
      autoGenTimerRef.current = null;
    }
    setFormData({});
    setExtractedText('');
    setExtractedData(null);
    setResult('');
    setError('');
    setStage('idle');
    setAutoGenerated(false);
    setUploadedFileName('');
    setProgress(0);
    setProgressLabel('');
  }, []);

  useEffect(() => {
    return () => {
      if (autoGenTimerRef.current) {
        clearTimeout(autoGenTimerRef.current);
      }
    };
  }, []);

  return {
    formData, updateField, extractedText, extractedData, loading,
    result, error, viewerOpen, setViewerOpen,
    handleExtracted, handleGenerate, handleSaveDocument, setFormData,
    stage, autoGenerated, uploadedFileName, resetFlow,
    handleSaveToCase, cases, clients,
    handleDescriptionSubmit, handleDownloadPDF, handleDownloadDOC,
    progress, progressLabel,
  };
}

export function DraftingView({ config }: DraftingViewProps) {
  const {
    formData, updateField, extractedText, extractedData, loading,
    result, error, viewerOpen, setViewerOpen,
    handleExtracted, handleGenerate, handleSaveDocument,
    stage, autoGenerated, uploadedFileName, resetFlow,
    handleSaveToCase, cases,
    handleDescriptionSubmit, handleDownloadPDF, handleDownloadDOC,
    progress, progressLabel,
  } = useAutonomousDrafting(config);

  const [saveDialogOpen, setSaveDialogOpen] = useState(false);
  const [description, setDescription] = useState('');
  const Icon = config.icon;
  const hasAnyField = Object.values(formData).some(v => v && v.trim());

  return (
    <div className="space-y-4 max-w-4xl mx-auto">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
          <Icon className="h-6 w-6 text-primary" />
          {config.title}
        </h1>
        <p className="text-sm text-muted-foreground mt-1">{config.description}</p>
      </div>

      {/* Upload + Describe Card — Primary Actions */}
      <Card className={`border-2 transition-all duration-300 ${stage === 'done' ? 'border-primary/30 bg-primary/5' : stage === 'generating' || stage === 'extracting' ? 'border-primary/50 border-dashed' : 'border-border/50'}`}>
        <CardContent className="p-4 space-y-4">
          {stage === 'idle' && (
            <>
              {/* Autonomous AI Banner */}
              <div className="flex items-center gap-2 mb-2">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10">
                  <Zap className="h-4 w-4 text-primary" />
                </div>
                <div>
                  <p className="text-sm font-semibold">Autonomous AI Drafting</p>
                  <p className="text-[11px] text-muted-foreground">Upload a document or describe the issue — AI extracts, fills &amp; drafts automatically</p>
                </div>
              </div>

              {/* Progress bar for description flow */}
              {stage !== 'idle' && (
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-muted-foreground">{progressLabel}</span>
                    <Badge variant="outline" className="text-[10px]">{Math.round(progress)}%</Badge>
                  </div>
                  <Progress value={progress} className="h-1.5" />
                </div>
              )}

              {/* Document Upload */}
              <DocumentUpload module={config.module} onExtracted={handleExtracted} />

              <div className="relative">
                <div className="absolute inset-0 flex items-center">
                  <Separator className="w-full" />
                </div>
                <div className="relative flex justify-center text-[10px] uppercase">
                  <span className="bg-card px-2 text-muted-foreground">or describe the issue</span>
                </div>
              </div>

              {/* Description Input */}
              <div className="space-y-2">
                <div className="flex items-center gap-1.5">
                  <MessageSquare className="h-3.5 w-3.5 text-muted-foreground" />
                  <span className="text-xs font-medium">Describe the case or issue</span>
                </div>
                <Textarea
                  placeholder={`e.g., My client ${config.module === 'criminal' ? 'was arrested under Section 420 IPC' : config.module === 'family' ? 'wants to file for mutual consent divorce' : config.module === 'execution' ? 'has a decree from City Civil Court that needs execution' : 'is the plaintiff in a property dispute case'}. ${config.module === 'criminal' ? 'FIR No. 123/2024, PS: Central, accused: Raj Kumar...' : 'Provide party names, addresses, case details...'} AI will extract everything and draft the ${config.title.toLowerCase()}.`}
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  rows={3}
                  className="resize-none"
                />
                <Button
                  onClick={() => handleDescriptionSubmit(description)}
                  disabled={loading || !description.trim()}
                  className="gap-2 w-full"
                >
                  {loading ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <Sparkles className="h-4 w-4" />
                  )}
                  {loading ? 'Analyzing...' : 'AI Extract & Draft'}
                </Button>
              </div>

              <div className="relative">
                <div className="absolute inset-0 flex items-center">
                  <Separator className="w-full" />
                </div>
                <div className="relative flex justify-center text-[10px] uppercase">
                  <span className="bg-card px-2 text-muted-foreground">or fill manually</span>
                </div>
              </div>
            </>
          )}

          {/* Extracting / Generating Progress */}
          {(stage === 'extracting' || stage === 'generating') && (
            <div className="flex flex-col items-center py-6 gap-3">
              <div className="relative">
                <div className="h-16 w-16 rounded-full border-4 border-primary/20 flex items-center justify-center">
                  <Loader2 className="h-8 w-8 animate-spin text-primary" />
                </div>
                <div className="absolute -bottom-1 -right-1 h-6 w-6 rounded-full bg-primary/10 flex items-center justify-center">
                  <Sparkles className="h-3 w-3 text-primary" />
                </div>
              </div>
              <div className="text-center">
                <p className="text-sm font-semibold animate-pulse">
                  {stage === 'extracting' ? 'AI is extracting data...' : `AI is generating your ${config.title.toLowerCase()}`}
                </p>
                <p className="text-xs text-muted-foreground mt-1">{progressLabel}</p>
              </div>
              <div className="w-48 h-1.5 bg-muted rounded-full overflow-hidden">
                <div
                  className="h-full bg-primary rounded-full transition-all duration-500 ease-out"
                  style={{ width: `${progress}%` }}
                />
              </div>
            </div>
          )}

          {/* Success State */}
          {stage === 'done' && (
            <div className="flex items-center gap-3 py-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 shrink-0">
                <CheckCircle2 className="h-5 w-5 text-primary" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold text-primary">Document Generated Successfully</p>
                <p className="text-xs text-muted-foreground truncate">
                  {uploadedFileName ? `From: ${uploadedFileName}` : description ? `From description` : 'AI-generated draft ready'}
                </p>
              </div>
              <Button variant="outline" size="sm" className="gap-1.5 text-xs shrink-0" onClick={resetFlow}>
                <RotateCcw className="h-3 w-3" /> New
              </Button>
            </div>
          )}

          {/* Error State */}
          {stage === 'error' && (
            <div className="flex items-center gap-3 py-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-destructive/10 shrink-0">
                <Scale className="h-5 w-5 text-destructive" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold text-destructive">Generation Failed</p>
                <p className="text-xs text-muted-foreground truncate">{error}</p>
              </div>
              <Button variant="outline" size="sm" className="gap-1.5 text-xs shrink-0" onClick={resetFlow}>
                <RotateCcw className="h-3 w-3" /> Retry
              </Button>
            </div>
          )}

          {/* Form Fields — always accessible */}
          {stage !== 'generating' && (
            <div className="space-y-3">
              {config.formFields.map((field, idx) => {
                const isLastHalf = field.half && idx < config.formFields.length - 1 && config.formFields[idx + 1]?.half;
                if (field.half && idx % 2 === 0 && isLastHalf) {
                  const nextField = config.formFields[idx + 1];
                  return (
                    <div key={field.key} className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      <div className="space-y-1.5">
                        <Label className="text-xs">{field.label}</Label>
                        <Input
                          placeholder={field.placeholder}
                          value={formData[field.key] || ''}
                          onChange={(e) => updateField(field.key, e.target.value)}
                        />
                      </div>
                      <div className="space-y-1.5">
                        <Label className="text-xs">{nextField.label}</Label>
                        <Input
                          placeholder={nextField.placeholder}
                          value={formData[nextField.key] || ''}
                          onChange={(e) => updateField(nextField.key, e.target.value)}
                        />
                      </div>
                    </div>
                  );
                }
                if (field.half && idx % 2 === 1) return null;

                if (field.type === 'textarea') {
                  return (
                    <div key={field.key} className="space-y-1.5">
                      <Label className="text-xs">{field.label}</Label>
                      <Textarea
                        placeholder={field.placeholder}
                        value={formData[field.key] || ''}
                        onChange={(e) => updateField(field.key, e.target.value)}
                        rows={4}
                        className="resize-none"
                      />
                    </div>
                  );
                }

                return (
                  <div key={field.key} className="space-y-1.5">
                    <Label className="text-xs">{field.label}</Label>
                    <Input
                      placeholder={field.placeholder}
                      value={formData[field.key] || ''}
                      onChange={(e) => updateField(field.key, e.target.value)}
                    />
                  </div>
                );
              })}

              {/* Manual Generate Button */}
              {(hasAnyField && !result && !loading) && (
                <>
                  <Separator className="my-2" />
                  <div className="flex items-center gap-3">
                    <Button onClick={handleGenerate} disabled={loading} className="gap-2">
                      {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
                      {loading ? 'Generating...' : 'Generate Draft'}
                    </Button>
                  </div>
                </>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Extracted Data Preview */}
      {extractedData && (stage === 'extracting' || stage === 'generating') && (
        <Card className="border-primary/20 bg-primary/5 animate-in fade-in-0 slide-in-from-bottom-1 duration-200">
          <CardContent className="p-3 space-y-2">
            <div className="flex items-center gap-2">
              <Sparkles className="h-3.5 w-3.5 text-primary" />
              <span className="text-xs font-medium">AI Extracted Data</span>
              <Badge variant="outline" className="text-[10px] ml-auto">Auto-filling fields...</Badge>
            </div>
            <div className="grid grid-cols-2 gap-1.5">
              {Object.entries(extractedData)
                .filter(([_, v]) => v !== null && v !== undefined && v !== '')
                .slice(0, 10)
                .map(([key, value]) => (
                  <div key={key} className="text-[10px]">
                    <span className="text-muted-foreground capitalize">{key.replace(/([A-Z])/g, ' $1')}:</span>
                    <span className="ml-1 font-medium">
                      {Array.isArray(value) ? value.join(', ') : String(value).substring(0, 50)}
                    </span>
                  </div>
                ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Result Card with PDF/DOC download */}
      {result && (
        <Card className="border-primary/20 bg-primary/5 animate-in fade-in-0 slide-in-from-bottom-2 duration-300">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between flex-wrap gap-2">
              <CardTitle className="text-sm flex items-center gap-2">
                <FileText className="h-4 w-4 text-primary" />
                Generated {config.title}
                {autoGenerated && <Badge variant="outline" className="text-[10px] text-primary border-primary/30">Auto-Generated</Badge>}
              </CardTitle>
              <div className="flex gap-1.5 flex-wrap">
                <Button size="sm" variant="outline" className="gap-1.5 text-xs" onClick={() => setViewerOpen(true)}>
                  <Eye className="h-3.5 w-3.5" /> View
                </Button>
                <Button size="sm" variant="outline" className="gap-1.5 text-xs" onClick={() => setViewerOpen(true)}>
                  <Pencil className="h-3.5 w-3.5" /> Edit
                </Button>
                <Button size="sm" variant="outline" className="gap-1.5 text-xs" onClick={handleDownloadPDF}>
                  <FileDown className="h-3.5 w-3.5" /> PDF
                </Button>
                <Button size="sm" variant="outline" className="gap-1.5 text-xs" onClick={handleDownloadDOC}>
                  <Download className="h-3.5 w-3.5" /> DOC
                </Button>
                {cases.length > 0 && (
                  <Button size="sm" variant="outline" className="gap-1.5 text-xs" onClick={() => setSaveDialogOpen(true)}>
                    <Save className="h-3.5 w-3.5" /> Save to Case
                  </Button>
                )}
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <ScrollArea className="max-h-[500px]">
              <MarkdownContent content={result} />
            </ScrollArea>
          </CardContent>
        </Card>
      )}

      {/* Save to Case Dialog */}
      <Dialog open={saveDialogOpen} onOpenChange={setSaveDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Save Document to Case</DialogTitle>
            <DialogDescription>Select a case to save this generated document to.</DialogDescription>
          </DialogHeader>
          <div className="space-y-2 max-h-[300px] overflow-y-auto">
            {cases.length === 0 ? (
              <p className="text-sm text-muted-foreground text-center py-4">No cases found. Create a case first.</p>
            ) : (
              cases.map((c) => (
                <button
                  key={c.id}
                  onClick={() => { handleSaveToCase(c.id); setSaveDialogOpen(false); }}
                  className="w-full flex items-center gap-3 p-3 rounded-lg border hover:bg-accent transition-colors text-left"
                >
                  <Briefcase className="h-4 w-4 text-muted-foreground shrink-0" />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium truncate">{c.title}</p>
                    <p className="text-[10px] text-muted-foreground">{c.caseType} • {c.status}</p>
                  </div>
                </button>
              ))
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" size="sm" onClick={() => setSaveDialogOpen(false)}>Cancel</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Document Viewer Dialog */}
      <DocumentViewer
        open={viewerOpen}
        onOpenChange={setViewerOpen}
        title={config.title}
        content={result}
        onSave={handleSaveDocument}
      />
    </div>
  );
}
