'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from '@/components/ui/dialog';
import { toast } from 'sonner';
import { apiCall, getAuthToken } from '@/lib/api-client';
import { DocumentUpload } from '@/components/shared/document-upload';
import { DocumentViewer } from '@/components/shared/document-viewer';
import { MarkdownContent } from '@/components/shared/markdown-content';
import { useAppStore } from '@/store/app-store';
import { useClientsStore } from '@/store/clients-store';
import { v4 as uuidv4 } from 'uuid';
import {
  Loader2, Scale, Sparkles, FileText, Download, Save, Briefcase, Users, CheckCircle2,
  Zap, ArrowDown, RotateCcw, FileDown, Eye, Pencil
} from 'lucide-react';

interface FormField {
  key: string;
  label: string;
  placeholder: string;
  type?: 'text' | 'textarea' | 'date' | 'number';
  half?: boolean;
}

interface ViewConfig {
  title: string;
  description: string;
  icon: React.ElementType;
  apiEndpoint: string;
  apiTask?: string;
  documentType?: string;
  module: 'civil' | 'criminal' | 'family' | 'execution';
  formFields: FormField[];
  getResultContent: (res: any) => string;
}

interface DraftingViewProps {
  config: ViewConfig;
}

type FlowStage = 'idle' | 'uploaded' | 'extracting' | 'generating' | 'done' | 'error';

function useAutonomousDrafting(config: ViewConfig) {
  const [formData, setFormData] = useState<Record<string, string>>({});
  const [extractedText, setExtractedText] = useState('');
  const [extractedData, setExtractedData] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState('');
  const [error, setError] = useState('');
  const [viewerOpen, setViewerOpen] = useState(false);
  const [stage, setStage] = useState<FlowStage>('idle');
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [uploadedFileName, setUploadedFileName] = useState('');
  const autoGenTimerRef = useRef<NodeJS.Timeout | null>(null);

  const cases = useAppStore((s) => s.cases);
  const clients = useClientsStore((s) => s.clients);
  const addDocument = useAppStore((s) => s.addDocument);

  const updateField = (key: string, value: string) => {
    setFormData((prev) => ({ ...prev, [key]: value }));
  };

  // CORE AUTONOMOUS FLOW: After extraction, auto-trigger generation
  const handleExtracted = useCallback((data: { text: string; structuredData: any }) => {
    setExtractedText(data.text);
    setExtractedData(data.structuredData);
    setUploadedFileName(data.fileName || '');
    setStage('extracting');

    // Auto-fill ALL form fields from extracted data
    if (data.structuredData) {
      const newFormData: Record<string, string> = {};
      config.formFields.forEach((field) => {
        const val =
          data.structuredData[field.key] ||
          data.structuredData[field.key.toLowerCase()] ||
          data.structuredData[field.label.toLowerCase()] ||
          data.structuredData[field.label.replace(/\s+/g, '').toLowerCase()] ||
          '';
        if (val) {
          newFormData[field.key] = Array.isArray(val) ? val.join(', ') : String(val);
        }
      });
      // Also try to extract from nested objects (parties, accused, etc.)
      const sd = data.structuredData;
      // Map common fields from intake-style extraction
      if (sd.accusedName && config.formFields.find(f => f.key === 'accusedName')) {
        newFormData.accusedName = newFormData.accusedName || sd.accusedName;
      }
      if (sd.applicantName && config.formFields.find(f => f.key === 'applicantName')) {
        newFormData.applicantName = newFormData.applicantName || sd.applicantName;
      }
      if (sd.complainantName && config.formFields.find(f => f.key === 'complainantName')) {
        newFormData.complainantName = newFormData.complainantName || sd.complainantName;
      }
      if (sd.petitionerName && config.formFields.find(f => f.key === 'petitionerName')) {
        newFormData.petitionerName = newFormData.petitionerName || sd.petitionerName;
      }
      if (sd.plaintiffName && config.formFields.find(f => f.key === 'plaintiffName')) {
        newFormData.plaintiffName = newFormData.plaintiffName || sd.plaintiffName;
      }
      if (sd.defendantName && config.formFields.find(f => f.key === 'defendantName')) {
        newFormData.defendantName = newFormData.defendantName || sd.defendantName;
      }
      if (sd.respondentName && config.formFields.find(f => f.key === 'respondentName')) {
        newFormData.respondentName = newFormData.respondentName || sd.respondentName;
      }
      if (sd.prosecutorName && config.formFields.find(f => f.key === 'prosecutorName')) {
        newFormData.prosecutorName = newFormData.prosecutorName || sd.prosecutorName;
      }
      if (sd.firNumber && config.formFields.find(f => f.key === 'firNumber')) {
        newFormData.firNumber = newFormData.firNumber || sd.firNumber;
      }
      if (sd.policeStation && config.formFields.find(f => f.key === 'policeStation')) {
        newFormData.policeStation = newFormData.policeStation || sd.policeStation;
      }
      if (sd.courtName && config.formFields.find(f => f.key === 'courtName')) {
        newFormData.courtName = newFormData.courtName || sd.courtName;
      }
      if (sd.sections && config.formFields.find(f => f.key === 'sectionsCharged')) {
        newFormData.sectionsCharged = newFormData.sectionsCharged || (Array.isArray(sd.sections) ? sd.sections.join(', ') : sd.sections);
      }
      if (sd.underSections && config.formFields.find(f => f.key === 'sectionsCharged')) {
        newFormData.sectionsCharged = newFormData.sectionsCharged || (Array.isArray(sd.underSections) ? sd.underSections.join(', ') : sd.underSections);
      }
      if (sd.causeOfAction && config.formFields.find(f => f.key === 'causeOfAction')) {
        newFormData.causeOfAction = newFormData.causeOfAction || sd.causeOfAction;
      }
      if (sd.facts && config.formFields.find(f => f.key === 'facts')) {
        newFormData.facts = newFormData.facts || (Array.isArray(sd.facts) ? sd.facts.join('\n') : sd.facts);
      }
      if (sd.facts && config.formFields.find(f => f.key === 'matterFacts')) {
        newFormData.matterFacts = newFormData.matterFacts || (Array.isArray(sd.facts) ? sd.facts.join('\n') : sd.facts);
      }
      if (sd.grounds && config.formFields.find(f => f.key === 'grounds')) {
        newFormData.grounds = newFormData.grounds || (Array.isArray(sd.grounds) ? sd.grounds.join('\n') : sd.grounds);
      }
      if (sd.reliefSought && config.formFields.find(f => f.key === 'reliefSought')) {
        newFormData.reliefSought = newFormData.reliefSought || sd.reliefSought;
      }
      if (sd.prayer && config.formFields.find(f => f.key === 'prayer')) {
        newFormData.prayer = newFormData.prayer || sd.prayer;
      }
      if (sd.impugnedOrder && config.formFields.find(f => f.key === 'impugnedOrder')) {
        newFormData.impugnedOrder = newFormData.impugnedOrder || sd.impugnedOrder;
      }
      if (sd.fundamentalRights && config.formFields.find(f => f.key === 'fundamentalRights')) {
        newFormData.fundamentalRights = newFormData.fundamentalRights || (Array.isArray(sd.fundamentalRights) ? sd.fundamentalRights.join(', ') : sd.fundamentalRights);
      }
      if (sd.natureOfViolence && config.formFields.find(f => f.key === 'natureOfViolence')) {
        newFormData.natureOfViolence = newFormData.natureOfViolence || sd.natureOfViolence;
      }
      if (sd.reliefSought && config.formFields.find(f => f.key === 'reliefSought')) {
        newFormData.reliefSought = newFormData.reliefSought || (Array.isArray(sd.reliefSought) ? sd.reliefSought.join('\n') : sd.reliefSought);
      }
      if (sd.subjectMatter && config.formFields.find(f => f.key === 'subjectMatter')) {
        newFormData.subjectMatter = newFormData.subjectMatter || sd.subjectMatter;
      }
      if (sd.parties && Array.isArray(sd.parties)) {
        sd.parties.forEach((p: any, i: number) => {
          if (i === 0 && p.role?.toLowerCase().includes('plaintiff') && config.formFields.find(f => f.key === 'plaintiffName')) {
            newFormData.plaintiffName = newFormData.plaintiffName || p.name;
            newFormData.plaintiffAddress = newFormData.plaintiffAddress || p.address;
          }
          if (i === 0 && p.role?.toLowerCase().includes('defendant') && config.formFields.find(f => f.key === 'defendantName')) {
            newFormData.defendantName = newFormData.defendantName || p.name;
            newFormData.defendantAddress = newFormData.defendantAddress || p.address;
          }
        });
      }
      if (sd.opposingParties && Array.isArray(sd.opposingParties) && sd.opposingParties.length > 0) {
        const op = sd.opposingParties[0];
        if (config.formFields.find(f => f.key === 'respondentName')) {
          newFormData.respondentName = newFormData.respondentName || op.name;
        }
        if (config.formFields.find(f => f.key === 'defendantName')) {
          newFormData.defendantName = newFormData.defendantName || op.name;
        }
      }

      setFormData(prev => ({ ...prev, ...newFormData }));
    }

    // AUTO-GENERATE: After extraction, automatically generate the draft
    // Small delay for UX so user sees the extraction happen
    setStage('generating');
    autoGenTimerRef.current = setTimeout(() => {
      performGenerate(data.text, { ...formData, ...data.structuredData });
    }, 800);
  }, [config.formFields]);

  const performGenerate = useCallback(async (extractedContent: string, mergedData: Record<string, string>) => {
    setLoading(true);
    setResult('');
    setError('');
    setStage('generating');
    try {
      const body: any = {};
      if (config.apiTask) body.task = config.apiTask;
      if (config.documentType) body.documentType = config.documentType;
      if (extractedContent) body.extractedText = extractedContent;
      // Include all form data + extracted data
      Object.keys(mergedData).forEach((k) => {
        const val = mergedData[k];
        if (val && typeof val === 'string' && val.trim()) body[k] = val;
      });

      const token = getAuthToken();
      const res = await apiCall(config.apiEndpoint, body, token || undefined);
      const content = config.getResultContent(res);
      setResult(content);
      setStage('done');
      setAutoGenerated(true);
      toast.success('Document generated successfully');
    } catch (err: any) {
      setError(err?.message || 'Generation failed');
      setStage('error');
      toast.error(err?.message || 'Failed to generate document');
    }
    setLoading(false);
  }, [config]);

  const handleGenerate = useCallback(async () => {
    // Clear any pending auto-generation
    if (autoGenTimerRef.current) {
      clearTimeout(autoGenTimerRef.current);
      autoGenTimerRef.current = null;
    }
    await performGenerate(extractedText, formData);
  }, [extractedText, formData, performGenerate]);

  const handleSaveDocument = (content: string) => {
    setResult(content);
    toast.success('Document updated');
  };

  const handleSaveToCase = (caseId: string) => {
    if (!result || !caseId) return;
    const docItem = {
      id: uuidv4(),
      name: `${config.title} - ${new Date().toLocaleDateString('en-IN')}`,
      type: 'draft',
      category: config.module,
      content: result,
      caseId,
      createdAt: new Date().toISOString(),
    };
    addDocument(docItem);
    toast.success('Document saved to case');
  };

  const resetFlow = useCallback(() => {
    if (autoGenTimerRef.current) {
      clearTimeout(autoGenTimerRef.current);
      autoGenTimerRef.current = null;
    }
    setFormData({});
    setExtractedText('');
    setExtractedData(null);
    setResult('');
    setError('');
    setStage('idle');
    setAutoGenerated(false);
    setUploadedFileName('');
  }, []);

  // Cleanup timer on unmount
  useEffect(() => {
    return () => {
      if (autoGenTimerRef.current) {
        clearTimeout(autoGenTimerRef.current);
      }
    };
  }, []);

  return {
    formData, updateField, extractedText, extractedData, loading,
    result, error, viewerOpen, setViewerOpen,
    handleExtracted, handleGenerate, handleSaveDocument, setFormData,
    stage, autoGenerated, uploadedFileName, resetFlow,
    handleSaveToCase, cases, clients,
  };
}

export function DraftingView({ config }: DraftingViewProps) {
  const {
    formData, updateField, extractedText, extractedData, loading,
    result, error, viewerOpen, setViewerOpen,
    handleExtracted, handleGenerate, handleSaveDocument,
    stage, autoGenerated, uploadedFileName, resetFlow,
    handleSaveToCase, cases,
  } = useAutonomousDrafting(config);

  const [saveDialogOpen, setSaveDialogOpen] = useState(false);
  const Icon = config.icon;
  const hasAnyField = Object.values(formData).some(v => v && v.trim());

  return (
    <div className="space-y-4 max-w-4xl mx-auto">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
          <Icon className="h-6 w-6 text-primary" />
          {config.title}
        </h1>
        <p className="text-sm text-muted-foreground mt-1">{config.description}</p>
      </div>

      {/* Upload Card — Primary Action */}
      <Card className={`border-2 transition-all duration-300 ${stage === 'done' ? 'border-primary/30 bg-primary/5' : stage === 'generating' ? 'border-primary/50 border-dashed animate-pulse' : 'border-border/50'}`}>
        <CardContent className="p-4 space-y-4">
          {stage === 'idle' && (
            <>
              <div className="flex items-center gap-2 mb-2">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10">
                  <Zap className="h-4 w-4 text-primary" />
                </div>
                <div>
                  <p className="text-sm font-semibold">Autonomous AI Drafting</p>
                  <p className="text-[11px] text-muted-foreground">Upload a document — AI extracts, fills &amp; drafts automatically</p>
                </div>
              </div>
              <DocumentUpload module={config.module} onExtracted={handleExtracted} />

              <div className="relative">
                <div className="absolute inset-0 flex items-center">
                  <Separator className="w-full" />
                </div>
                <div className="relative flex justify-center text-[10px] uppercase">
                  <span className="bg-card px-2 text-muted-foreground">or fill manually</span>
                </div>
              </div>
            </>
          )}

          {/* Generating Progress */}
          {stage === 'generating' && (
            <div className="flex flex-col items-center py-6 gap-3">
              <div className="relative">
                <div className="h-16 w-16 rounded-full border-4 border-primary/20 flex items-center justify-center">
                  <Loader2 className="h-8 w-8 animate-spin text-primary" />
                </div>
                <div className="absolute -bottom-1 -right-1 h-6 w-6 rounded-full bg-primary/10 flex items-center justify-center">
                  <Sparkles className="h-3 w-3 text-primary" />
                </div>
              </div>
              <div className="text-center">
                <p className="text-sm font-semibold animate-pulse">AI is generating your {config.title.toLowerCase()}</p>
                <p className="text-xs text-muted-foreground mt-1">Extracting data, filling fields, and drafting the document...</p>
              </div>
              <div className="w-48 h-1.5 bg-muted rounded-full overflow-hidden">
                <div className="h-full bg-primary rounded-full animate-[loading_2s_ease-in-out_infinite]" style={{ width: '60%' }} />
              </div>
            </div>
          )}

          {/* Success State */}
          {stage === 'done' && (
            <div className="flex items-center gap-3 py-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 shrink-0">
                <CheckCircle2 className="h-5 w-5 text-primary" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold text-primary">Document Generated Successfully</p>
                <p className="text-xs text-muted-foreground truncate">{uploadedFileName ? `From: ${uploadedFileName}` : 'AI-generated draft ready'}</p>
              </div>
              <Button variant="outline" size="sm" className="gap-1.5 text-xs shrink-0" onClick={resetFlow}>
                <RotateCcw className="h-3 w-3" /> New
              </Button>
            </div>
          )}

          {/* Error State */}
          {stage === 'error' && (
            <div className="flex items-center gap-3 py-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-destructive/10 shrink-0">
                <Scale className="h-5 w-5 text-destructive" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold text-destructive">Generation Failed</p>
                <p className="text-xs text-muted-foreground truncate">{error}</p>
              </div>
              <Button variant="outline" size="sm" className="gap-1.5 text-xs shrink-0" onClick={resetFlow}>
                <RotateCcw className="h-3 w-3" /> Retry
              </Button>
            </div>
          )}

          {/* Form Fields — always accessible */}
          {stage !== 'generating' && (
            <div className="space-y-3">
              {config.formFields.map((field, idx) => {
                const isLastHalf = field.half && idx < config.formFields.length - 1 && config.formFields[idx + 1]?.half;
                if (field.half && idx % 2 === 0 && isLastHalf) {
                  const nextField = config.formFields[idx + 1];
                  return (
                    <div key={field.key} className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      <div className="space-y-1.5">
                        <Label className="text-xs">{field.label}</Label>
                        <Input
                          placeholder={field.placeholder}
                          value={formData[field.key] || ''}
                          onChange={(e) => updateField(field.key, e.target.value)}
                        />
                      </div>
                      <div className="space-y-1.5">
                        <Label className="text-xs">{nextField.label}</Label>
                        <Input
                          placeholder={nextField.placeholder}
                          value={formData[nextField.key] || ''}
                          onChange={(e) => updateField(nextField.key, e.target.value)}
                        />
                      </div>
                    </div>
                  );
                }
                if (field.half && idx % 2 === 1) return null;

                if (field.type === 'textarea') {
                  return (
                    <div key={field.key} className="space-y-1.5">
                      <Label className="text-xs">{field.label}</Label>
                      <Textarea
                        placeholder={field.placeholder}
                        value={formData[field.key] || ''}
                        onChange={(e) => updateField(field.key, e.target.value)}
                        rows={4}
                        className="resize-none"
                      />
                    </div>
                  );
                }

                return (
                  <div key={field.key} className="space-y-1.5">
                    <Label className="text-xs">{field.label}</Label>
                    <Input
                      placeholder={field.placeholder}
                      value={formData[field.key] || ''}
                      onChange={(e) => updateField(field.key, e.target.value)}
                    />
                  </div>
                );
              })}

              {/* Manual Generate Button (shown when fields are filled but no auto-gen) */}
              {(hasAnyField && !result && !loading && stage !== 'generating') && (
                <>
                  <Separator className="my-2" />
                  <div className="flex items-center gap-3">
                    <Button onClick={handleGenerate} disabled={loading} className="gap-2">
                      {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
                      {loading ? 'Generating...' : 'Generate Draft'}
                    </Button>
                  </div>
                </>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Extracted Data Preview (shown during extraction) */}
      {extractedData && stage !== 'done' && stage !== 'error' && (
        <Card className="border-primary/20 bg-primary/5 animate-in fade-in-0 slide-in-from-bottom-1 duration-200">
          <CardContent className="p-3 space-y-2">
            <div className="flex items-center gap-2">
              <Sparkles className="h-3.5 w-3.5 text-primary" />
              <span className="text-xs font-medium">AI Extracted Data</span>
              <Badge variant="outline" className="text-[10px] ml-auto">Auto-filling fields...</Badge>
            </div>
            <div className="grid grid-cols-2 gap-1.5">
              {Object.entries(extractedData)
                .filter(([_, v]) => v !== null && v !== undefined && v !== '')
                .slice(0, 10)
                .map(([key, value]) => (
                  <div key={key} className="text-[10px]">
                    <span className="text-muted-foreground capitalize">{key.replace(/([A-Z])/g, ' $1')}:</span>
                    <span className="ml-1 font-medium">
                      {Array.isArray(value) ? value.join(', ') : String(value).substring(0, 50)}
                    </span>
                  </div>
                ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Result Card */}
      {result && (
        <Card className="border-primary/20 bg-primary/5 animate-in fade-in-0 slide-in-from-bottom-2 duration-300">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm flex items-center gap-2">
                <FileText className="h-4 w-4 text-primary" />
                Generated {config.title}
                {autoGenerated && <Badge variant="outline" className="text-[10px] text-primary border-primary/30">Auto-Generated</Badge>}
              </CardTitle>
              <div className="flex gap-1.5">
                <Button size="sm" variant="outline" className="gap-1.5 text-xs" onClick={() => setViewerOpen(true)}>
                  <Eye className="h-3.5 w-3.5" /> View
                </Button>
                <Button size="sm" variant="outline" className="gap-1.5 text-xs" onClick={() => setViewerOpen(true)}>
                  <Pencil className="h-3.5 w-3.5" /> Edit
                </Button>
                {cases.length > 0 && (
                  <Button size="sm" variant="outline" className="gap-1.5 text-xs" onClick={() => setSaveDialogOpen(true)}>
                    <Save className="h-3.5 w-3.5" /> Save to Case
                  </Button>
                )}
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <ScrollArea className="max-h-[500px]">
              <MarkdownContent content={result} />
            </ScrollArea>
          </CardContent>
        </Card>
      )}

      {/* Save to Case Dialog */}
      <Dialog open={saveDialogOpen} onOpenChange={setSaveDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Save Document to Case</DialogTitle>
            <DialogDescription>Select a case to save this generated document to.</DialogDescription>
          </DialogHeader>
          <div className="space-y-2 max-h-[300px] overflow-y-auto">
            {cases.length === 0 ? (
              <p className="text-sm text-muted-foreground text-center py-4">No cases found. Create a case first.</p>
            ) : (
              cases.map((c) => (
                <button
                  key={c.id}
                  onClick={() => { handleSaveToCase(c.id); setSaveDialogOpen(false); }}
                  className="w-full flex items-center gap-3 p-3 rounded-lg border hover:bg-accent transition-colors text-left"
                >
                  <Briefcase className="h-4 w-4 text-muted-foreground shrink-0" />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium truncate">{c.title}</p>
                    <p className="text-[10px] text-muted-foreground">{c.caseType} • {c.status}</p>
                  </div>
                </button>
              ))
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" size="sm" onClick={() => setSaveDialogOpen(false)}>Cancel</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Document Viewer Dialog */}
      <DocumentViewer
        open={viewerOpen}
        onOpenChange={setViewerOpen}
        title={config.title}
        content={result}
        onSave={handleSaveDocument}
      />
    </div>
  );
}
